steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/slackbot-288310/secretary-bot-v2", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/slackbot-288310/secretary-bot-v2"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "secretary-bot-v2",
        "--image",
        "gcr.io/slackbot-288310/secretary-bot-v2",
        "--region",
        "asia-northeast1",
        "--allow-unauthenticated",
        "--update-env-vars",
        "USER_ID=${_USER_ID}",
        "--service-account",
        "secretary-bot-v2@slackbot-288310.iam.gserviceaccount.com"
      ]
images:
  - gcr.io/slackbot-288310/secretary-bot-v2
